spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  ## MYSQL
  datasource:
    url: jdbc:mysql://210.109.63.18:10011
    username: admin
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

  logging:
    level:
      org.hibernate.SQL:debug

## JWT SECRET ##
secret:
    jwt_secret_key: dsafdfasdfsdasew2r-*k.ap9kje-wxBHb9wdXsdgsadgsdaerwrqwer-Nu

## serverName ##
server:
  url: libertyform_api.shop
