spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  ## MYSQL ##
  datasource:
    url: jdbc:mysql://210.109.63.18:10011/liberty_form-api
    username: admin
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #차후 수정할 것
    properties:
      hibernate:
        format_sql: true
        show_sql: true
# ses 설정
aws:
  ses:
    access-key: ASDSD123SAD
    secret-key: 4353453fsafdSF234sdf

## Jwt Secret ##
secret:
    jwt_secret_key: dsafdfasdfsdasew2r-*k.ap9kje-wxBHb9wdXsdgsadgsdaerwrqwer-Nu

## serverName ##
server:
  url: libertyform.shop
  ## 서버 리다이렉트 설정 (Https)
  tomcat:
    use-relative-redirects: true

## Kakao i Cloud Secret ##
cloud:
  kakao:
    access_key: 12fa54725a7b4d77a8667c788ffee0ce
    secret_key: hiVxHmMGoxipkiU6Mo4AVg1cqrfosLBaZv-ddP3BImrSbqNeGhd9lK9DDw6Ga5N1jydi0UHHvEM25fNFACaJAA

## log4j
logging:
  config: classpath:log4j2.yml